/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;

import org.apache.commons.cli.Options;

public class App {

    public static void main(String[] args) {
        //Create options object
        Options options = new Options();

        //Add options
        options.addOption("h", false, "usage: eval [OPTIONS]\n" +
                "Evaluation of simple mathematical expressions\n" +
                "\n" +
                "-b,--batch <file>    batch file containing expressions to evaluate\n" +
                "-h,--help            print usage message\n" +
                "-o,--output <file>   output file\n");
        options.addOption("b", true, "Batch value: lib");
        options.addOption("o", true, "Output value: lib");
    }
}
